name: CI-CD

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v2

      # Set up Java
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      # Build JAR file
      - name: Build the jar file
        run: ./mvnw clean package -DskipTests

      # Log in to ACR (no secrets in code!)
      - name: Azure Container Registry login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # Build and push Docker image
      - name: Build and push image
        run: |
          docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/myapp:${{ github.sha }} .
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/myapp:${{ github.sha }}

      # Deploy the image to ACI
      - name: Deploy to ACI
        run: |
          az container create --resource-group samidGroup --name ${{ secrets.REGISTRY_USERNAME }} 
          --image testregistrysamid.azurecr.io/testapp:latest --dns-name-label testapisamid --ports 8080 --registry-login-server ${{ secrets.REGISTRY_LOGIN_SERVER }} --registry-username testregistrysamid --registry-password V2j6WZNbhLJw90Jxxr0TCZbxfclKybyGYPK7u58LMI+ACRCIqco3 --os-type linux --cpu 1 --memory 1.5
